name: local
values:
  - key: build_service
    value: 'http://localhost:8087'
  - key: user_service
    value: 'http://localhost:8082'
  - key: api_gateway
    value: 'http://localhost:8080'
  - key: auth_service
    value: 'http://localhost:8081'
  - key: category_service
    value: 'http://localhost:8084'
  - key: compatibility_service
    value: 'http://localhost:8085'
  - key: estimate_service
    value: 'http://localhost:8088'
  - key: hardware_advisor_service
    value: 'http://localhost:8089'
  - key: notification_service
    value: 'http://localhost:8090'
  - key: product_service
    value: 'http://localhost:8083'
  - key: provider_service
    value: 'http://localhost:8086'
